local M = {}

function M.get(c, opts)
  return {
    Normal = {
      bg = opts.transparent and "NONE" or c.bg,
      fg = c.fg,
    },
    NormalFloat = {
      bg = opts.transparent and "NONE" or c.bg,
      fg = c.fg,
    },
    NormalNC = {
      bg = opts.transparent and "NONE" or c.bg,
      fg = c.fg,
    },
    FloatBorder = { fg = c.float_border, bg = opts.transparent and "NONE" or c.bg },
    FloatTitle = {
      bg = opts.transparent and "NONE" or c.bg,
      fg = c.silver,
    },
    WinBar = { bg = opts.transparent and "NONE" or c.bg },
    WinBarNC = { bg = opts.transparent and "NONE" or c.bg },
    ColorColumn = { bg = c.black },
    Conceal = { fg = c.grey },
    Cursor = { bg = c.fg, fg = c.bg },
    CurSearch = { bg = c.signal, fg = c.bg },
    IncSearch = { bg = c.signal, fg = c.bg },
    CursorColumn = { bg = opts.transparent and "NONE" or c.bg_alt },
    CursorLine = { bg = opts.transparent and "NONE" or c.cursor_line.bg },
    CursorLineNr = { bg = opts.transparent and "NONE" or c.cursor_line_nr.bg, fg = c.cursor_line_nr.fg },
    Directory = { fg = c.silver },
    DiffAdd = c.git.add,
    DiffChange = c.git.change,
    DiffDelete = c.git.delete,
    DiffText = { fg = c.git.text.fg, bg = c.git.text.bg },
    Error = { fg = c.error },
    ErrorMsg = { fg = c.error },
    VertSplit = { fg = c.float_bg },
    Folded = { fg = c.grey_light, bg = c.selection },
    FoldColumn = { fg = c.comment, bg = opts.transparent and "NONE" or c.bg_soft },
    SignColumn = { fg = c.comment },
    LineNr = { fg = c.line_nr },
    MatchParen = { fg = c.grey_light },
    ModeMsg = { fg = c.ok },
    NonText = { fg = c.comment },
    Pmenu = { fg = c.fg, bg = c.bg },
    PmenuSel = { bg = c.selection },
    PmenuSbar = { bg = c.bg },
    PmenuThumb = { bg = c.border },
    PmenuKind = { fg = c.func, bg = c.bg },
    PmenuKindSel = { fg = c.func, bg = c.selection },
    PmenuExtra = { fg = c.grey_light, bg = c.bg },
    PmenuExtraSel = { fg = c.grey_light, bg = c.selection },
    Question = { fg = c.ok },
    QuickFixLine = { bg = c.selection },
    Search = { fg = c.fg_bright, bg = c.bg_plum },
    SpecialKey = { fg = c.border, bg = c.bg_alt },
    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.cream, undercurl = true },
    SpellLocal = { sp = c.grey_mid, undercurl = true },
    SpellRare = { sp = c.grey_mid, undercurl = true },
    StatusLine = { fg = c.white, bg = opts.transparent and "NONE" or c.bg_alt },
    StatusLineNC = { fg = c.silver, bg = opts.transparent and "NONE" or c.bg_alt },
    TabLine = { fg = c.grey_pale, bg = opts.transparent and "NONE" or c.bg_alt },
    TabLineFill = { bg = opts.transparent and "NONE" or c.bg_alt, fg = c.grey_mid },
    TabLineSel = { fg = c.ok, bg = c.black },
    Title = { fg = c.ok },
    Visual = { bg = c.visual },
    WinSeparator = { fg = c.bg_alt },
    MsgSeparator = { fg = c.float_bg, bg = opts.transparent and "NONE" or c.bg },

    GitSignsAddVirtLnInLine = c.git.add,
    GitSignsChangeVirtLnInLine = c.git.change,
    GitSignsDeleteVirtLnInLine = c.git.delete,

    DiagnosticError = { fg = c.diag.error },
    DiagnosticUnderlineError = { undercurl = true, sp = c.diag.error },
    DiagnosticWarn = { fg = c.diag.warning },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.diag.warning },
    DiagnosticInfo = { fg = c.diag.info },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.diag.info },
    DiagnosticHint = { fg = c.diag.hint },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.diag.hint },
    DiagnosticOk = { fg = c.diag.ok },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.diag.ok },
    DiagnosticUnnecessary = { fg = c.keyword, undercurl = true },
  }
end

return M
